---
- hosts: terraform-ansible
  tasks:
    - name: Criar servidor HTTP
      become: yes
      shell: |
        sudo yum install -y httpd
        sudo systemctl start httpd
        sudo systemctl enable httpd

    - name: Adicionar usuário ao grupo apache
      become: yes
      user:
        name: "{{ ansible_ssh_user }}"
        groups: apache
        append: yes

    - name: Criar diretório /var/www/html
      become: yes
      file:
        path: /var/www/html
        state: directory
        mode: "0755"
        owner: apache
        group: apache

    - name: Criar arquivo index.html
      become: yes
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Feito com Terraform e Ansible</h1>"
        owner: apache
        group: apache
