---
- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      yum:
        name:
        - python3
        - python3-pip
        - python3-virtualenv
      become: yes

    - name: Criar diretório /tcc
      file:
        path: /tcc
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: Instalando dependências com pip (Django e django rest)
      pip:
        virtualenv: /tcc/venv
        name:
          - django
          - djangorestframework
      become: yes

    - name: Iniciando projeto
      shell: '. /tcc/venv/bin/activate; django-admin startproject setup /tcc/'
    - name: Alterando hosts do settings
      lineinfile: 
        path: /tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]' 
        backrefs: yes

